stages:
  - build
  - lint
  - test

check:
  stage: build
  parallel:
    matrix:
      - image: [rust:latest, rustlang/rust:nightly]
  image: ${image}
  script:
    - cargo check --verbose

test:
  stage: test
  extends: lint
  parallel:
    matrix:
      - image: [rust:latest, rustlang/rust:nightly]
        feature: ["", "std"]
  image: ${image}
  script:
    - cargo test --no-default-features --features=${feature}

test_ignored:
  stage: test
  extends: lint
  image: "rust:latest"
  script:
    - cargo test -- --ignored

clippy:
  stage: lint
  extends: build
  image: "rust:latest"
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all

fmt:
  stage: lint
  extends: build
  image: "rust:latest"
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check
